from enum import StrEnum


class ErrorCode(StrEnum):
	STALE_STATE = "STALE_STATE"
	MALFORMED_STATE = "MALFORMED_STATE"
	UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
	FINISHED_GAME = "FINISHED_GAME"
	ILLEGAL_MOVE = "ILLEGAL_MOVE"
	DB_ERROR = "DB_ERROR"


class PostgresErrorCode(StrEnum):
	UNIQUE_CONSTRAINT_VIOLATION = "23505"